version: '3.8'
services:
  jupyter:
    build:
      context: ./jupyter
    container_name: climate-jupyter
    ports:
      - 8888:8888
    links:
      - db
    volumes:
      - "./notebooks:/data"

  geoserver:
    image: docker.osgeo.org/geoserver:2.21.1
    container_name: climate-geoserver
    ports:
      - 80:8080
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw,wmts-multi-dimensional,gdal
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
    volumes:
      - ./geoserver/geoserver_data:/opt/geoserver_data/:Z
      # - ./additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup

  db:
    image: postgis/postgis
    restart: always
    container_name: climate-db
    environment:
      POSTGRES_PASSWORD: climate_change
      POSTGRES_USER: climate_change
      POSTGRES_DB: climate
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    networks:
      - backdb
    expose:
      - 5433

  front:
    build: ./climate-front
    volumes:
      - './climate-front:/climate-front'
    image: climate/climate-front
    container_name: climate-front
    ports:
      - '3000:3000'
    networks:
      - frontback

networks:
  backdb:
    driver: bridge
  frontback:
    driver: bridge
