version: '3.8'
services:
  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    links:
      - db
    volumes:
      - "./notebooks:/data"

  geoserver:
    image: docker.osgeo.org/geoserver:2.21.1

    # build:
    #   context: ./geoserver
    #   args:
    #     - GEOSERVER_VERSION=2.21.1
    #     - CORS_ENABLED=true
    #     - CORS_ALLOWED_METHODS=GET,POST,PUT,HEAD,OPTIONS
    ports:
      - 80:8080
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw,wmts-multi-dimensional,gdal
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
    volumes:
      - ./geoserver/geoserver_data:/opt/geoserver_data/:Z
      # - ./additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup

  db:
    image: postgis/postgis
    restart: always
    container_name: climate-docker-db
    environment:
      POSTGRES_PASSWORD: climate_change
      POSTGRES_USER: climate_change
      POSTGRES_DB: climate
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    networks:
      - backdb
    expose:
      - 5433

  front:
    build: ./climate-front
      # context: ./climate-front
      # dockerfile: Dockerfile
    volumes:
      - './climate-front:/climate-front'
    image: climate/climate-front
    container_name: climate-front
    ports:
      - '5003:5003'
    # depends_on:
    #   - back
    networks:
      - frontback

networks:
  backdb:
    driver: bridge
  frontback:
    driver: bridge
