name: climaxto
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python==3.9
  - numpy
  - pandas
  - geopandas
  - seaborn
  - scikit-learn
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - requests
  - nb_conda_kernels
  - scikit-learn-intelex
  - geemap
  - leafmap
  - eefolium
  - rasterio
  - xarray
  - shapely
  - fiona
  - earthengine-api
  - netcdf4
  - h5netcdf
  - conda-forge:
    - xarray 
    - dask
    - netCDF4
    - bottleneck
    - rioxarray
    

